export const Design = [
    {image: '/image/3D/corridor.png'},
    {image: '/image/3D/crystal1.png'},
    {image: '/image/3D/garden.png'},
    {image: '/image/3D/kitchenset1.png'},
    {image: '/image/3D/kitchenset2.png'},
    {image: '/image/3D/kunoichi.png'},
    {image: '/image/3D/livingroom.png'},
    {image: '/image/3D/royalty.png'},
    {image: '/image/3D/s15.png'},
    {image: '/image/3D/door.png'},
    {image: '/image/3D/thorneroom.png'},
    {image: '/image/3D/train.png'},
    {image: '/image/3D/scifi.png'},
    {image: '/image/3D/royalty1.png'},
    {image: '/image/3D/royalty2.png'},
    {image: '/image/3D/royalty3.png'},
    {image: '/image/3D/prototype3.png'},
    {image: '/image/3D/lowpoly.png'},
    {image: '/image/3D/library.png'},
    {image: '/image/3D/lab.png'},
    {image: '/image/3D/klinik.png'},
    {image: '/image/3D/home.png'},
    {image: '/image/3D/done.png'},
    {image: '/image/3D/cube.png'},

];