export const Design = [
    {image: '/image/3D/corridor old.png'},
    {image: '/image/3D/crystal1.png'},
    {image: '/image/3D/garden.png'},
    {image: '/image/3D/kitchen set 2 new angle.png'},
    {image: '/image/3D/kitchen set.png'},
    {image: '/image/3D/kunoichi test.png'},
    {image: '/image/3D/living room.png'},
    {image: '/image/3D/royalty.png'},
    {image: '/image/3D/s15.png'},
    {image: '/image/3D/suzume no tojimari.png'},
    {image: '/image/3D/throne room.png'},
    {image: '/image/3D/train japan.png'},
    {image: '/image/3D/scifi done.png'},
    {image: '/image/3D/royality type 2.1.png'},
    {image: '/image/3D/royality type 2.png'},
    {image: '/image/3D/royality type 3.png'},
    {image: '/image/3D/prototype3.png'},
    {image: '/image/3D/low poly room.png'},
    {image: '/image/3D/library.png'},
    {image: '/image/3D/lab.png'},
    {image: '/image/3D/klinik.png'},
    {image: '/image/3D/home.png'},
    {image: '/image/3D/done.png'},
    {image: '/image/3D/default cube.png'},

];