// AUTO-GENERATED from github.com/SyuQyu via gh CLI. Do not hand-edit;
// regenerate with scratchpad/gen-projects.mjs when repos change.

export interface GithubProject {
    id: string;
    name: string;
    repo: string;
    live: string;
    language: string;
    stars: number;
    year: string;
    description: string;
    detail: string;
    topics: string[];
    featured: boolean;
}

export const githubProjects: GithubProject[] = [
    {
        "id": "bot-character-ai",
        "name": "Bot Character AI",
        "repo": "https://github.com/SyuQyu/bot-character-ai",
        "live": "",
        "language": "JavaScript",
        "stars": 2,
        "year": "2024",
        "description": "",
        "detail": "This Discord bot allows users to interact with various AI characters using text commands. The bot uses the Node.js Discord.js library for interacting with Discord's API and the node characterai library for communicating with the AI characters. List characters available for interaction. Select a character to interact with. Chat with the selected character. Generate an image based on the conversation with certain characters. Get help on available commands. 1. Clone the repository: 2. Install dependencies: 3. Set up environment variables: sessionTokenFromCharacterId : Session token for authentica",
        "topics": [],
        "featured": true
    },
    {
        "id": "portofolio-3d-website",
        "name": "Portofolio 3d Website",
        "repo": "https://github.com/SyuQyu/portofolio-3d-website",
        "live": "",
        "language": "JavaScript",
        "stars": 1,
        "year": "2022",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": true
    },
    {
        "id": "Simple-Web",
        "name": "Simple Web",
        "repo": "https://github.com/SyuQyu/Simple-Web",
        "live": "",
        "language": "JavaScript",
        "stars": 1,
        "year": "2022",
        "description": "",
        "detail": "Aplikasi Web Based Yang Dikerjakan oleh 5 Orang : Pandu, Jesselyn, Aqil, Teguh, Fajar Untuk Menjalankan Program Web ini silahkan install package terlebih dahulu dengan cara: npm install di FE & BE, Setelah itu Jalankan dengan npm start.",
        "topics": [],
        "featured": true
    },
    {
        "id": "portofolio-pandu-2023",
        "name": "Portofolio Pandu 2023",
        "repo": "https://github.com/SyuQyu/portofolio-pandu-2023",
        "live": "https://portofolio-pandu-2023.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": true
    },
    {
        "id": "porto-web",
        "name": "Porto Web",
        "repo": "https://github.com/SyuQyu/porto-web",
        "live": "https://porto-web-phi.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": true
    },
    {
        "id": "app-fe-freelance",
        "name": "APP FE Freelance",
        "repo": "https://github.com/SyuQyu/app-fe-freelance",
        "live": "https://app-fe-freelance.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "Dashboard Design Request Project (Copy) This is a code bundle for Dashboard Design Request Project (Copy). The original project is available at https://www.figma.com/design/qENyRm6ANmUOkkfISmOiDz/Dashboard Design Request Project Copy . Running the code Run npm i to install the dependencies. Run npm run dev to start the development server.",
        "topics": [],
        "featured": true
    },
    {
        "id": "workfrom-fe",
        "name": "Workfrom FE",
        "repo": "https://github.com/SyuQyu/workfrom-fe",
        "live": "https://workfrom-fe.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": true
    },
    {
        "id": "company-profile-mni",
        "name": "Company Profile MNI",
        "repo": "https://github.com/SyuQyu/company-profile-mni",
        "live": "https://company-profile-mni.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "Company Profile for PT. Mega Nusa Indonesia made by Etech. 1. Clone this repo. 2. Run yarn install to install dependencies. 3. Go to the project directory. 4. Run yarn start . yarn dev Run the application yarn build Build the application yarn lint Run ESLint yarn lint:fix Fix codes from ESLint errors yarn format Format codes using Prettier To learn more about Next.js, take a look at the following resources: Next.js Documentation learn about Next.js features and API. Learn Next.js an interactive Next.js tutorial. You can check out the Next.js GitHub repository your feedback and contributions ar",
        "topics": [],
        "featured": true
    },
    {
        "id": "Backend-AI",
        "name": "Backend AI",
        "repo": "https://github.com/SyuQyu/Backend-AI",
        "live": "https://backend-ai-eight.vercel.app",
        "language": "Python",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "API ini melakukan parafrase (pengubahan kalimat dengan makna tetap) untuk teks Bahasa Indonesia menggunakan model HuggingFace T5 ( cahya/t5 base indonesian summarization cased ). Request: Maksimal 500 karakter. Response: Response: Response: 1. Install dependensi: 2. Jalankan aplikasi: 3. Akses endpoint: Paraphrase: POST http://localhost:8000/paraphrase Health check: GET http://localhost:8000/health Model: cahya/t5 base indonesian summarization cased Tokenizer: T5Tokenizer dari HuggingFace, mengubah teks ke token. Model: T5ForConditionalGeneration , tipe encoder decoder untuk sequence to sequen",
        "topics": [],
        "featured": true
    },
    {
        "id": "web-mama",
        "name": "Web Mama",
        "repo": "https://github.com/SyuQyu/web-mama",
        "live": "https://erni-products.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "An e commerce web application developed with Next.JS and TypeScript. Tailwind CSS is used for styling and React's Context API is used for state management. Custom REST API is used as a backend (Haru API). Progressive Web App (PWA) 🔥 Full text Search 🔎 Responsive Design 📱💻 Wishlist 🤍 Add To Cart 🛒 Different Category Page 🧑🏻👩🏻🎒 Authentication (Register/Login/Logout) 🛡️ Pagination ⬅️➡️ Animation ✨ i18n (English & Burmese) 🌐 Keyboard Accessible ⌨️ Frontend NextJS, React, TypeScript Styling Tailwind CSS Design & Prototype Figma State Management ContextAPI Backend Haru API (Previous Ver",
        "topics": [],
        "featured": true
    },
    {
        "id": "gorest-fetch-api",
        "name": "GOREST Fetch API",
        "repo": "https://github.com/SyuQyu/gorest-fetch-api",
        "live": "https://gorest-fetch-api.vercel.app",
        "language": "TypeScript",
        "stars": 0,
        "year": "2023",
        "description": "",
        "detail": "Ini adalah panduan langkah demi langkah tentang cara menjalankan program Anda secara lokal menggunakan Yarn. Pertama, Anda perlu mengunduh atau mengklon kode sumber program Anda dari repositori versi kontrol (misalnya, Git). Anda dapat melakukannya dengan perintah berikut: Setelah Anda memiliki kode sumber program di komputer Anda, langkah berikutnya adalah menginstal semua dependensi yang diperlukan. Lakukan ini dengan perintah:",
        "topics": [],
        "featured": true
    },
    {
        "id": "invitation-digital",
        "name": "Invitation Digital",
        "repo": "https://github.com/SyuQyu/invitation-digital",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "template-web",
        "name": "Template Web",
        "repo": "https://github.com/SyuQyu/template-web",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "project-ganteng",
        "name": "Project Ganteng",
        "repo": "https://github.com/SyuQyu/project-ganteng",
        "live": "",
        "language": "",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "discord-bot",
        "name": "Discord Bot",
        "repo": "https://github.com/SyuQyu/discord-bot",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "MassSender",
        "name": "Mass Sender",
        "repo": "https://github.com/SyuQyu/MassSender",
        "live": "",
        "language": "HTML",
        "stars": 0,
        "year": "2026",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "CR-BARENG",
        "name": "CR BARENG",
        "repo": "https://github.com/SyuQyu/CR-BARENG",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "backend-skripsi-2025",
        "name": "Backend Skripsi 2025",
        "repo": "https://github.com/SyuQyu/backend-skripsi-2025",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "frontend-skripsi-2025",
        "name": "Frontend Skripsi 2025",
        "repo": "https://github.com/SyuQyu/frontend-skripsi-2025",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "backend-skripsi",
        "name": "Backend Skripsi",
        "repo": "https://github.com/SyuQyu/backend-skripsi",
        "live": "",
        "language": "",
        "stars": 0,
        "year": "2025",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "FY24_Front-End-Developer_Type-B",
        "name": "FY24 Front End Developer Type B",
        "repo": "https://github.com/SyuQyu/FY24_Front-End-Developer_Type-B",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "basic-form-nextjs",
        "name": "Basic Form Nextjs",
        "repo": "https://github.com/SyuQyu/basic-form-nextjs",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "linnaapp",
        "name": "Linnaapp",
        "repo": "https://github.com/SyuQyu/linnaapp",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "linnaappbackend",
        "name": "Linnaappbackend",
        "repo": "https://github.com/SyuQyu/linnaappbackend",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "backend-e-canteen",
        "name": "Backend E Canteen",
        "repo": "https://github.com/SyuQyu/backend-e-canteen",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "frontend-e-canteen",
        "name": "Frontend E Canteen",
        "repo": "https://github.com/SyuQyu/frontend-e-canteen",
        "live": "",
        "language": "",
        "stars": 0,
        "year": "2024",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "final-project-sc-backend-2023",
        "name": "Final Project SC Backend 2023",
        "repo": "https://github.com/SyuQyu/final-project-sc-backend-2023",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2023",
        "description": "Tugas final project untuk kelas Backend Basic 2023",
        "detail": "Tugas final project untuk kelas Backend Basic 2023",
        "topics": [],
        "featured": false
    },
    {
        "id": "MadinaInventoryApp",
        "name": "Madina Inventory APP",
        "repo": "https://github.com/SyuQyu/MadinaInventoryApp",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2023",
        "description": "Projek Inventory Management untuk Madina Baja",
        "detail": "Projek Inventory Management untuk Madina Baja",
        "topics": [],
        "featured": false
    },
    {
        "id": "mini-project-tsc-backend-2023",
        "name": "Mini Project TSC Backend 2023",
        "repo": "https://github.com/SyuQyu/mini-project-tsc-backend-2023",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2023",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "inventory-app-fe",
        "name": "Inventory APP FE",
        "repo": "https://github.com/SyuQyu/inventory-app-fe",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2023",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "workfrom-be",
        "name": "Workfrom BE",
        "repo": "https://github.com/SyuQyu/workfrom-be",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2023",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "workfrom-api-init",
        "name": "Workfrom API Init",
        "repo": "https://github.com/SyuQyu/workfrom-api-init",
        "live": "",
        "language": "PHP",
        "stars": 0,
        "year": "2023",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "maxy-academy-2023",
        "name": "Maxy Academy 2023",
        "repo": "https://github.com/SyuQyu/maxy-academy-2023",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2023",
        "description": "bootcamp maxy academy 2023",
        "detail": "bootcamp maxy academy 2023",
        "topics": [],
        "featured": false
    },
    {
        "id": "movie-api-fetch-api.tvmaze",
        "name": "Movie API Fetch API Tvmaze",
        "repo": "https://github.com/SyuQyu/movie-api-fetch-api.tvmaze",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2023",
        "description": "nextjs for movie api fetch from api.tvmaze",
        "detail": "nextjs for movie api fetch from api.tvmaze",
        "topics": [],
        "featured": false
    },
    {
        "id": "netherbound",
        "name": "Netherbound",
        "repo": "https://github.com/SyuQyu/netherbound",
        "live": "",
        "language": "ShaderLab",
        "stars": 0,
        "year": "2023",
        "description": "git for project netherbound",
        "detail": "git for project netherbound",
        "topics": [],
        "featured": false
    },
    {
        "id": "ProjectAkhirPemrogramanWeb",
        "name": "Project Akhir Pemrograman Web",
        "repo": "https://github.com/SyuQyu/ProjectAkhirPemrogramanWeb",
        "live": "",
        "language": "PHP",
        "stars": 0,
        "year": "2023",
        "description": "Pemrograman Web",
        "detail": "Pemrograman Web",
        "topics": [],
        "featured": false
    },
    {
        "id": "basic-api",
        "name": "Basic API",
        "repo": "https://github.com/SyuQyu/basic-api",
        "live": "",
        "language": "TypeScript",
        "stars": 0,
        "year": "2022",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "twitter-clone",
        "name": "Twitter Clone",
        "repo": "https://github.com/SyuQyu/twitter-clone",
        "live": "",
        "language": "Vue",
        "stars": 0,
        "year": "2022",
        "description": "First Project Using Nuxtjs",
        "detail": "First Project Using Nuxtjs",
        "topics": [],
        "featured": false
    },
    {
        "id": "image-generator-web",
        "name": "Image Generator Web",
        "repo": "https://github.com/SyuQyu/image-generator-web",
        "live": "",
        "language": "Vue",
        "stars": 0,
        "year": "2022",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "ChatApp",
        "name": "Chat APP",
        "repo": "https://github.com/SyuQyu/ChatApp",
        "live": "",
        "language": "HTML",
        "stars": 0,
        "year": "2022",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    },
    {
        "id": "WeCare",
        "name": "We Care",
        "repo": "https://github.com/SyuQyu/WeCare",
        "live": "",
        "language": "JavaScript",
        "stars": 0,
        "year": "2022",
        "description": "",
        "detail": "",
        "topics": [],
        "featured": false
    }
];
