export const codingPortfolio = [
    { id: '1', title: 'Company Profile', subtitle: 'Freelance', description: 'In this project, I am tasked with creating a company profile website for PT. Mega Nusa Indonesia. My primary responsibility is to proficiently translate the user interface (UI) design into a fully functional website using NextJS framework.', projectLink: { github: '', hosting: '' }, image: '/image/coding/compro.png' },
    { id: '2', title: 'Website Iro Iro Station', subtitle: 'Part Time', description: 'In this project, I have been assigned to developing an administrative dashboard for Iro Iro Station. My primary task entails translating the provided UI design into a comprehensive and fully functional website. and I am required to implement the necessary backend components.', projectLink: { github: '', hosting: '' }, image: '/image/coding/iroiro.jpeg' },
    { id: '3', title: 'Gemastik 2022 Ankersal', subtitle: 'competition', description: 'In this project, I am tasked with creating a  website for Anti-Sexual Violence primary responsibility is to proficiently translate the user interface (UI) design into a fully functional website.', projectLink: { github: '', hosting: '' }, image: '/image/coding/ankersal.jpeg' },

];

export const threeDPortfolio = [
    {
        id: '1',
        title: '3D Project 1',
        subtitle: 'Information 1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/corridor.png',
    },
    {
        id: '2',
        title: '3D Project 2',
        subtitle: 'Information 2',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/crystal1.png',
    },
    {
        id: '3',
        title: '3D Project 3',
        subtitle: 'Information 3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/garden.png',
    },
    {
        id: '4',
        title: '3D Project 4',
        subtitle: 'Information 4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/kitchenset1.png',
    },
    {
        id: '5',
        title: '3D Project 5',
        subtitle: 'Information 5',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/kitchenset2.png',
    },
    {
        id: '6',
        title: '3D Project 6',
        subtitle: 'Information 6',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/kunoichi.png',
    },
    {
        id: '7',
        title: '3D Project 7',
        subtitle: 'Information 7',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/livingroom.png',
    },
    {
        id: '8',
        title: '3D Project 8',
        subtitle: 'Information 8',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/royalty.png',
    },
    {
        id: '9',
        title: '3D Project 9',
        subtitle: 'Information 9',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/s15.png',
    },
    {
        id: '10',
        title: '3D Project 10',
        subtitle: 'Information 10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/door.png',
    },
    {
        id: '11',
        title: '3D Project 11',
        subtitle: 'Information 11',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/thorneroom.png',
    },
    {
        id: '12',
        title: '3D Project 12',
        subtitle: 'Information 12',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/train.png',
    },
    {
        id: '13',
        title: '3D Project 13',
        subtitle: 'Information 13',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/scifi.png',
    },
    {
        id: '14',
        title: '3D Project 14',
        subtitle: 'Information 14',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/royalty1.png',
    },
    {
        id: '15',
        title: '3D Project 15',
        subtitle: 'Information 15',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/royalty2.png',
    },
    {
        id: '16',
        title: '3D Project 16',
        subtitle: 'Information 16',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/royalty3.png',
    },
    {
        id: '17',
        title: '3D Project 17',
        subtitle: 'Information 17',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/prototype3.png',
    },
    {
        id: '18',
        title: '3D Project 18',
        subtitle: 'Information 18',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/lowpoly.png',
    },
    {
        id: '19',
        title: '3D Project 19',
        subtitle: 'Information 19',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/library.png',
    },
    {
        id: '20',
        title: '3D Project 20',
        subtitle: 'Information 20',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/lab.png',
    },
    {
        id: '21',
        title: '3D Project 21',
        subtitle: 'Information 21',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/klinik.png',
    },
    {
        id: '22',
        title: '3D Project 22',
        subtitle: 'Information 22',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/home.png',
    },
    {
        id: '23',
        title: '3D Project 23',
        subtitle: 'Information 23',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/done.png',
    },
    {
        id: '24',
        title: '3D Project 24',
        subtitle: 'Information 24',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        image: '/image/3D/cube.png',
    },
];